# Generated by Django 2.2.4 on 2019-09-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='daily_attendance_employee',
        ),
    ]
