# Generated by Django 2.2.4 on 2019-09-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190923_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_profile',
            name='edit_request_by_emp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee_profile',
            name='edit_request_by_hr',
            field=models.BooleanField(default=False),
        ),
    ]
