# Generated by Django 2.2.4 on 2019-09-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190923_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_employee_leaves',
            name='emp_cmpmy_email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tb_employee_leaves',
            name='emp_hr_email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tb_employee_leaves',
            name='leave_status',
            field=models.IntegerField(default=0),
        ),
    ]
