# Generated by Django 2.2.4 on 2019-09-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190923_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_employee_leaves',
            name='emp_cmpmy_email',
        ),
        migrations.RemoveField(
            model_name='tb_employee_leaves',
            name='emp_hr_email',
        ),
        migrations.AddField(
            model_name='tb_employee_leaves',
            name='casual_leaves',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='tb_employee_leaves',
            name='leaves_left',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tb_employee_leaves',
            name='medical_leaves',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='tb_employee_leaves',
            name='total_leaves',
            field=models.IntegerField(default=18),
        ),
    ]
