# Generated by Django 2.2.4 on 2019-09-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190923_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_employee_leaves',
            name='emp_cmpy_email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tb_employee_leaves',
            name='emp_hr_email',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='tb_employee_leaves',
            name='leaves_left',
            field=models.CharField(default='4.5', max_length=50),
        ),
    ]
