# Generated by Django 2.2.4 on 2019-09-23 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20190923_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tb_employee_leaves',
            old_name='leaves_left',
            new_name='leaves_left_monthly',
        ),
        migrations.AddField(
            model_name='tb_employee_leaves',
            name='leaves_left_total',
            field=models.IntegerField(default=18),
        ),
    ]
