# Generated by Django 2.2.4 on 2019-09-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20190923_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_employee_leaves',
            name='reason',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
