# Generated by Django 2.2.4 on 2019-09-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_tb_employee_leaves_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_employee_leaves',
            name='leave_policy_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
