# Generated by Django 2.2.4 on 2019-09-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20190923_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='daily_attendance_employee',
        ),
    ]
